### ISSUE TITLE
字典问题

### ISSUE THREAD

**Issue by xiaozhaha** [GhostTroops/ksubdomain#4]
合并 https://codeload.github.com/n0kovo/n0kovo_subdomains/zip/refs/heads/main 字典到 config/subdomain.txt,并优化其中无效数据
字典数量 累计 3065536 【306万+】个
请问下师傅，你这里说的字典数量 306万+ ，是已经打包在 ksubdomain 里面了，下载直接  ksubdomain v -d xx.com，就直接跑这306万+的字典吗？还是说要自己去那里下载这个，再指定字典文件名。

**Comment by xiaozhaha** [comment]
好像是已经加载进去了，我看发包总量是域名*306万+。

**Comment by hktalent** [comment]
默认打包进去了，运行是从config目录下的zip中释放出来使用
