### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by woshinibabao1** [GhostTroops/ksubdomain#5]
goroutine 39 [running]:
github.com/GhostTroops/go-utils.DoRunning()
	github.com/GhostTroops/go-utils@v0.0.0-20240128101636-18f19360e029/log2BigDb.go:46 +0xcb
created by github.com/GhostTroops/ksubdomain/runner.(*runner).handleResult in goroutine 37
	github.com/GhostTroops/ksubdomain/runner/result.go:9 +0x3d

**Comment by hktalent** [comment]
如何发生的？
不能同时运行多个 ksubdomain 实例
因为使用了 db 来做一些防重、提高性能，多实例会冲突

**Comment by woshinibabao1** [comment]
还有个小问题，./ksubdomain v -f ./subdomain.ret -o ./tmp/ksubdomain.ret3 --retry -1 我这样运行了三次，但是得到的结果差异巨大
![微信截图_20240514085532](https://github.com/GhostTroops/ksubdomain/assets/136443419/681083fe-78fb-4741-b070-4726a52db490)

**Comment by hktalent** [comment]
正常啊，多的结果不一定正常，很多时候可能是DNS 防火墙反馈的假的、错误的、导向蜜罐的数据
