### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by waydmy** [GhostTroops/ksubdomain#6]
go install -v github.com/hktalent/ksubdomain/cmd/ksubdomain@latest

go: github.com/hktalent/ksubdomain/cmd/ksubdomain@latest: module github.com/hktalent/ksubdomain@latest found (v0.0.0-20240322075136-288e794e122e), but does not contain package github.com/hktalent/ksubdomain/cmd/ksubdomain

**Comment by hktalent** [comment]
下载release，或者自己用github 到action在线编译
