### ISSUE TITLE
缓存文件过大

### ISSUE THREAD

**Issue by steveopen1** [GhostTroops/ksubdomain#8]
你好作者，请问为什么有一个缓存文件2gb

**Comment by hktalent** [comment]
感谢你的关注、反馈
这个问题之前也发现了，在windows下会有这个现象，也给缓存的组件官方反馈过，说是正常现象

本项目缓存目的：
1、避免重复
2、提高速度
3、默认情况下，执行会删除，win下可能自动删除失效，可以手工删除
